### ISSUE TITLE
look at the philosophical papers [add to spreadsheet]

### ISSUE THREAD

**Issue by rfl-urbaniak** [rfl-urbaniak/BayesBias#10]

**Comment by efemeryds** [comment]
https://www.gmjohnson.com/uploads/5/2/5/1/52514005/are_algorithms_value_free_.pdf

**Comment by efemeryds** [comment]
https://academic.oup.com/mind/article-abstract/129/516/1193/5841111?redirectedFrom=fulltext&login=false

**Comment by efemeryds** [comment]
https://arxiv.org/pdf/1811.07255.pdf

**Comment by efemeryds** [comment]
https://onlinelibrary.wiley.com/doi/10.1111/rode.12607
