### ISSUE TITLE
Discuss HMIEAI feedback

### ISSUE THREAD

**Issue by rfl-urbaniak** [rfl-urbaniak/BayesBias#14]
This is a short research paper, that combines a philosophical and technical contribution. The more or less philosophical question is whether or not uncertainty, which inherently is in the problem, should be taken into account in bias estimation. The authors argue that you should. They substantiate their arguments by pointing out the technical weaknesses in current approaches and demonstrate that a Bayesian approach gives different results. This seems to advocate for taking the effect of uncertainty seriously, for example by employing Bayesian methods. 

Now I would like to be able to summarize the authors' results, but unfortunately the main weakness of this paper is in the writing. A lot of information about how the simulation was done and how to interpret the results is missing. In addition, the authors also make a lot of claims that need further explanation. Let me just mention some:
- what do you mean by "mainstream interpretations are too hasty" (p1)
- "that such a move is important is suggested by Figure 1" (p2): not only are the figures unlabelled and without caption, so I have to guess which is which, there is no further explanation of how this follows from figure 1. Please help your reader with making explicit what you want us to note.
- where did you get your data from? Did you use the entire dataset? What control attributes did you use? What are "neutral non-human words"?
- when you randomly draw classes and attributes: what do you draw them from? And are these then syntatic data, or some sample of a standard data set?
- you do 10k simulations with a "more realistic word list sizes": please elaborate...what word list sizes? Why are these more realistic?
- Again, you refer to different figures, claiming they clearly demonstrate something, but I don't know exactly what you want me to take from these figures. Please provide more explanation.
- concerning your Bayesian model: what is the motivation for your choice of model (linear) and priors? How does the model incorporate the control groups, connection types? Which parameter represents what?
- you mention that (p3) "from this bayesian perspective the situation is much less obvious". What do you mean by "situation"? And in what sense are things "much less obvious" or "not very impressive"? Again, these questions may be trivially answered if you explain the figures.
- in the second to last paragraph you seem to discuss the results of applying bayesian models to some more datasets, but the results itself are not provided. Yet here you make quite detailed claims (e.g. "change [...] is really minor with zero still out of HPDI range". There is nothing to verify this claim; lack of space cannot be an excuse for being incomprehensible. 

Finally it would also help the readability of the paper if it is structured more explicitly rather than being one very long piece of text, and if the figures were actually numbered and had captions.

----------------------- REVIEW 2 ---------------------
SUBMISSION: 5839
TITLE: Taking uncertainty seriously - a  Bayesian approach to  word embedding bias estimation
AUTHORS: Alicja Dobrzeniecka and Rafal Urbaniak

----------- Overall evaluation -----------
SCORE: -1 (weak reject)
----- TEXT:
This short research paper look at bias estimation for word embeddings.
They look at standard ways of measuring these biases.
The authors mention two issues with such approaches; comparisons with control groups, and working on averaging away information such as sample size and variation.
The authors argue that this hamper the evaluation of bias, by e.g. giving users false confidence.
The contribution is to use a Bayesian model for estimating the mean bias in relation to different groups of attributes (e.g. to other stereotypical words, random words, or neutral words).
They experiment on word2vec embeddings, afaik.

It is difficult to evaluate the contributions of this paper.
First, the paper does not follow the given format guidelines (https://www.iospress.com/book-article-instructions), and is written without a clear structure that is easy to follow.
No figures are not numbered properly.
A major revision is completely necessary.
Second, there are many details missing in the descriptions of the method and experiments.
* Many phrases are vague and not backed up by explanations or references, e.g. "pre-averaging tends to manufacture false confidence".
* The results are difficult to interpret, as they are poorly presented and not explained properly.
* What the simulation is should be made more clear, as currently it is difficult to know what it is the reader should interpret from this.
* The design choices in how the Bayesian model is constructed are not motived enough.
* A more thorough literature review is necessary. AFAIK, Bayesian bias estimation is done in other domains of bias (e.g. "Bayesian Modeling of Intersectional Fairness: The Variance of Bias∗", or "The interaction effect of gender and ethnicity in loan approval: A Bayesian estimation with data from a laboratory field experiment").

The results might be interested, but a major revision of the presentation is needed for a thorough evaluation.

**Comment by efemeryds** [comment]
Main points from the comments:
- explaining **all** of the concepts, **assumptions** and conclusions in more detail so that it is easy for the reader to follow
- better motivation for the design choices
- more references to existing literature on Bayesian bias estimation
- explain in detail all of the figures and simulation results
